layout_spectrum: 0.6955089
color:
  saturation: 0.7378482
  lightness: 0.620364
  brandStrength: 0.6863799
  brandColors:
    - '#D7C9A2'
    - '#B5B79F'
    - '#96A995'
    - '#7A917E'
    - '#060625'
  rhythmicContrast: 0.4818268
typography_spectrum: 0.07168459
name: 'Canvases by Brooke '
